language: node_js
node_js:
- '12'
script: npm run-script build
deploy:
  provider: npm
  email: mail@appmanufacture.ch
  api_key:
    secure: dAT3Uj8Pt/d+yIhdcrbUE2GRSrmvUE8wuTNzQv1gFaQW3/QcMNgicjwyvRK/9I/8bApul+DSBUvAUFjNQ8JLbodWcy1d/VZaTx1hZ2XhAfS8Sv4AlV1mBzqaZFVOiUHe7w9HBpq4pwLvKnaIGKW2LM+XOEWh1rGuJkfoTjG9NNwJ+y0ay9TDxZ/oz2MWquEr+6NONHjHyxcQsrrkymIkCwfwNk88tN2K1YJKEl7kIPzRXUZ1aJmsB7dJ/U9aDKpVylcBILvlDMzkXDr2ThCa8pWTlT8HCtl0Wi2htpw70WPTGaLuXpWlfedwp6wfUss8NBf00ZvHN2F2z+dOgybgR07DbF3aGbytR031m5YSNJ47xYfdHSNIyIF1ZGfEHksCsejMBxNcxKE/eVU0PK5jZgmBHxAgMTN6NmANAWjoV0AhN2teInAytvr3pRtnX85fOnFFb8L0sgSFZNpixqY3mmzqKEvARA48UWe1y5goPN8AQW98WiSE1vZrJeKx6ooUicTuK4JxV4U1VBsQaK0sb3Wd0YZGy2xuhr3IMx2MpgZDG9e1kuBzKj1/RVTQDMq5AR8l1OjMzMN4KltZg0EWFlO6uXWCBI4CAOD3RdoD9XeI9UhWjQTYD9Br9m5q+dFcH74hkN3JBaBkeA98P4h1SdM+J7m+P6lICnyNOl0Kkl0=
  on:
    tags: true
    repo: cargomedia/janus-gateway-js
